### ISSUE TITLE
please share Gerber files with BOM and CPL so that we can order it from JLC pcb and please change to esp32

### ISSUE THREAD

**Issue by ark-brighthustle** [Renga-rider/WIFI-CONTROLLED-DRONE-V4#1]
please share Gerber files with BOM and CPL so that we can order it from JLC pcb and please change to esp32 and have a look at esp drone GitHub https://github.com/espressif/esp-drone and use this app to control drone

**Comment by Renga-rider** [comment]
Yeah sure
