### ISSUE TITLE
esp866 connection established, but motor not working

### ISSUE THREAD

**Issue by sreekanthmp** [Renga-rider/WIFI-CONTROLLED-DRONE-V4#2]
Esp866 connection established and code runs, the mpu accelerometer and gyro configuration sets . The Arm/Disarm button works fine in Blynk app but the motor not working when i give throttle,
![Diagram](https://user-images.githubusercontent.com/90472524/132893910-2947686b-fe8f-49d6-9f6b-91a5f77067e5.jpg)
here is my connection diagram

**Comment by Renga-rider** [comment]
It is for brushed motor for esc u need servo commands servo1.writeMicroseconds ()... Like that for all motors..
