### ISSUE TITLE
Motor issue

### ISSUE THREAD

**Issue by sreekanthmp** [Renga-rider/WIFI-CONTROLLED-DRONE-V4#3]
When I changed the code for bldc motor as you said, the motor connected to gpio14 only working.
![132893910-2947686b-fe8f-49d6-9f6b-91a5f77067e5](https://user-images.githubusercontent.com/90472524/136020825-6fb0adc8-430a-41e9-9fd1-f4cf97255578.jpg)

**Comment by Renga-rider** [comment]
USE 
servo.attach(PIN);
servo.writeMicroseconds(VALUE);
